CREATE DATABASE PP8;
USE PP8;

CREATE TABLE PRODUCT3
(
P_ID INT PRIMARY KEY AUTO_INCREMENT,
P_NAME VARCHAR(100),
CATEGORY VARCHAR(100),
PRICE DECIMAL(10,2)
);

INSERT INTO PRODUCT3
(P_NAME,CATEGORY,PRICE)
VALUES
('BIRIYANI','FOOD',150),
('COCOCOLA','DRINKS',120),
('NIKE','SHOE',1500),
('BMW','CAR',150000),
('G-SHOCK','WATCH',1000),
('MANDHI','FOOD',250),
('BALENO','CAR',130000),
('AUDI','CAR',550000);

WITH ProductRank AS
(
SELECT*,
DENSE_RANK()
OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC)AS RankNo
FROM PRODUCT3
)

SELECT *
FROM ProductRank
WHERE RankNo=2;